UHF-6142: Created a project listing paragraph and styled it
City-of-Helsinki/drupal-helfi-kymp pull request #421
Opened 2022-07-22 11:52 UTC by lonkaanna

# [UHF-6142](https://helsinkisolutionoffice.atlassian.net/browse/UHF-6142)

## What was done

* Created a project listing paragraph and styled it

## How to install

* Make sure your instance is up and running on correct branch.
  * `git pull origin UHF-6142-project-listing`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards
* [ ] Create some dummy projects to your local with the same district (more than 4 so you can test the load more feature )
* [ ] Add the new paragraph to a district page (upper content) and select the same district you added to the projects

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2022-08-03 13:22 UTC, teroelonen requested changes
Added some comments so that they are not forgotten :)

2022-08-03 13:22 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_project-list.scss
> +  list-style: none;
Alphabetic order mixed.

2022-08-03 13:22 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/templates/paragraph/paragraph--project-listing.html.twig
> +		{% endblock component_content %}
Indentation bit funny :)

2022-08-03 13:22 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/js/project-listing.js
> +(function ($, Drupal, drupalSettings) {
This is not needed if changing to view.

2022-08-04 08:56 UTC, tapsal approved these changes
Works great! 🦕

2022-08-09 08:56 UTC, teroelonen approved these changes
This is good to go now 🦖

2022-08-09 09:49 UTC, merged